version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    # https://dependabot.com/docs/config-file/#automerged_updates
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
      - match:
          dependency_type: "all"
          update_type: "in_range"
