version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
